### ISSUE TITLE
barnaserver down again

### ISSUE THREAD

**Issue by fransua** [gemtools/gemtools#24]
Hi,
it seems that barnaserver is not responding again... I guess it is a problem of the renewal of the domain.

**Comment by xnavrc** [comment]
Hi,
I have problem with downloading files from barnaserver. Do you know what should I do?

Downloading i3 bundle from http://barnaserver.com/gemtools//GEM-gemtools-1.7.1-i3.tar.gz to /opt/gemtools/downloads/GEM-gemtools-1.7.1-i3.tar.gz

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Error while extracting gem bundle

**Comment by thasso** [comment]
Hi,

unfortunately we had to move the server and the DNS entry was not properly updates ... we are on it.

Best,
-Thasso

**Comment by thasso** [comment]
The IP is update and it should work again.
