### ISSUE TITLE
installation failure with setup.py

### ISSUE THREAD

**Issue by podunn58** [gemtools/gemtools#35]
I have tried to install the stable binary, the cloned version from GitHub and the version on pip. In all cases I get the following error with the setup.py file.  Any ideas?  I have tried this on Ubuntu and Mac without success. 
Thanks for any help, Peter

pip install gemtools
Collecting gemtools
  Using cached https://files.pythonhosted.org/packages/8e/5a/3ed79b7649a5afc9fce8ed12298246069b7483d5e9a340248bc02ae660a2/Gemtools-1.7.1.tar.gz

File "setup.py", line 75
    print "copy jenkins build for", type
                                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("copy jenkins build for", type)?

**Comment by Poshi** [comment]
Probably you are trying to install under python 3. Try python 2.

--
Jordi Camps
jcamps@gmail.com

-----BEGIN GEEK CODE BLOCK-----
Version: 3.1
GCS/IT/S d-(+) s: a+ C++$>$ UL++ P---() L++ !E- W+ N+ !o K--? w+ !O !M !V
PS++() PE(-) Y+ !PGP>+++ t !5 X R tv(-) b+ DI+ D+ G e+++ h(---) r(--) y+**
------END GEEK CODE BLOCK------

**Comment by podunn58** [comment]
Hi
Thanks for the hint, but I am now getting an error message about security issues (i.e., SSL is required).  I tried setting up a virtual environment to install under Python 2.7, but it gave the new errors below.  See below for my commands and notes about what I did.  I will try this on a Mac next; I  was using Ubuntu for the commands below.
Any help is most appreciated.
Best,
Peter

U<http://pypi.python.org/pypi/virtualenv>sing virtualenv to run python2.7 instead of 3
from  https://stackoverflow.com/questions/7237415/python-2-instead-of-python-3-as-the-temporary-default-python#
 # Use this to create your temporary python "install"
# (Assuming that is the correct path to the python interpreter you want to use.)
 virtualenv -p /usr/bin/python2.7 --distribute temp-python
# Type this command when you want to use your temporary python.
# While you are using your temporary python you will also have access to a temporary pip,
# which will keep all packages installed with it separate from your main python install.
 source temp-python/bin/activate
 # When you no longer wish to use you temporary python type
deactivate
I followed the above instructions and then tried to use “pip install gemtools” again, but now I am getting a new security error
File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    urllib2.HTTPError: HTTP Error 403: SSL is required
       ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-5_nLN0/gemtools/
/home/manager/temp-python/local/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:160:
 InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this.
 For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
 below is urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings<http://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings>
  Certificate verification in Python 2
Older versions of Python 2 are built with an ssl<https://docs.python.org/3.5/library/ssl.html#module-ssl> module that lacks SNI support<https://urllib3.readthedocs.io/en/latest/advanced-usage.html#sni-warning> and can lag behind security updates. For these reasons it’s recommended to use pyOpenSSL<https://pyopenssl.readthedocs.io/en/latest/>.
If you install urllib3 with the secure extra, all required packages for certificate verification on Python 2 will be installed:
pip install urllib3[secure]  <- this did not work for me.  It did not accept the “[secure]” option.
If you want to install the packages manually, you will need pyOpenSSL, cryptography, idna, and certifi.
Note
If you are not using macOS or Windows, note that cryptography<https://cryptography.io/en/latest/> requires additional system packages to compile. See building cryptography on Linux<https://cryptography.io/en/latest/installation/#building-cryptography-on-linux> for the list of packages required.
Once installed, you can tell urllib3 to use pyOpenSSL by using urllib3.contrib.pyopenssl<https://urllib3.readthedocs.io/en/latest/reference/urllib3.contrib.html#module-urllib3.contrib.pyopenssl>:
>>> import urllib3.contrib.pyopenssl
>>> urllib3.contrib.pyopenssl.inject_into_urllib3()
Here are my subsequent commands:
(temp-python) manager@bl8vbox[manager] pip install urllib3[secure]                                                                                    [ 9:58PM]
zsh: no matches found: urllib3[secure]
(temp-python) manager@bl8vbox[manager] pip install cryptography                                                                                       [10:04PM]
Collecting cryptography
/home/manager/temp-python/local/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:369: SNIMissingWarning: An HTTPS request has been made, but the SNI (Server Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/home/manager/temp-python/local/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:160: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
/home/manager/temp-python/local/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:160: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
  Downloading https://files.pythonhosted.org/packages/87/e6/915a482dbfef98bbdce6be1e31825f591fc67038d4ee09864c1d2c3db371/cryptography-2.3.1-cp27-cp27mu-manylinux1_x86_64.whl (2.1MB)
    100% |████████████████████████████████| 2.1MB 6.6MB/s
Collecting six>=1.4.1 (from cryptography)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting enum34; python_version < "3" (from cryptography)
  Downloading https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting idna>=2.1 (from cryptography)
  Downloading https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 17.5MB/s
Collecting cffi!=1.11.3,>=1.7 (from cryptography)
  Downloading https://files.pythonhosted.org/packages/14/dd/3e7a1e1280e7d767bd3fa15791759c91ec19058ebe31217fe66f3e9a8c49/cffi-1.11.5-cp27-cp27mu-manylinux1_x86_64.whl (407kB)
    100% |████████████████████████████████| 409kB 21.2MB/s
Collecting asn1crypto>=0.21.0 (from cryptography)
  Downloading https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl (101kB)
    100% |████████████████████████████████| 102kB 15.2MB/s
Collecting ipaddress; python_version < "3" (from cryptography)
  Downloading https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Collecting pycparser (from cffi!=1.11.3,>=1.7->cryptography)
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
    100% |████████████████████████████████| 163kB 8.3MB/s
Building wheels for collected packages: pycparser
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /home/manager/.cache/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511
Successfully built pycparser
Installing collected packages: six, enum34, idna, pycparser, cffi, asn1crypto, ipaddress, cryptography
Successfully installed asn1crypto-0.24.0 cffi-1.11.5 cryptography-2.3.1 enum34-1.1.6 idna-2.7 ipaddress-1.0.22 pycparser-2.19 six-1.11.0

(temp-python) manager@bl8vbox[manager] pip install pyopenssl                                                                                          [10:16PM]
Collecting pyopenssl
/home/manager/temp-python/local/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:369: SNIMissingWarning: An HTTPS request has been made, but the SNI (Server Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/home/manager/temp-python/local/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:160: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
/home/manager/temp-python/local/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:160: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
  Downloading https://files.pythonhosted.org/packages/96/af/9d29e6bd40823061aea2e0574ccb2fcf72bfd6130ce53d32773ec375458c/pyOpenSSL-18.0.0-py2.py3-none-any.whl (53kB)
    100% |████████████████████████████████| 61kB 2.3MB/s
Requirement already satisfied: cryptography>=2.2.1 in ./temp-python/lib/python2.7/site-packages (from pyopenssl) (2.3.1)
Requirement already satisfied: six>=1.5.2 in ./temp-python/lib/python2.7/site-packages (from pyopenssl) (1.11.0)
Requirement already satisfied: enum34; python_version < "3" in ./temp-python/lib/python2.7/site-packages (from cryptography>=2.2.1->pyopenssl) (1.1.6)
Requirement already satisfied: idna>=2.1 in ./temp-python/lib/python2.7/site-packages (from cryptography>=2.2.1->pyopenssl) (2.7)
Requirement already satisfied: cffi!=1.11.3,>=1.7 in ./temp-python/lib/python2.7/site-packages (from cryptography>=2.2.1->pyopenssl) (1.11.5)
Requirement already satisfied: asn1crypto>=0.21.0 in ./temp-python/lib/python2.7/site-packages (from cryptography>=2.2.1->pyopenssl) (0.24.0)
Requirement already satisfied: ipaddress; python_version < "3" in ./temp-python/lib/python2.7/site-packages (from cryptography>=2.2.1->pyopenssl) (1.0.22)
Requirement already satisfied: pycparser in ./temp-python/lib/python2.7/site-packages (from cffi!=1.11.3,>=1.7->cryptography>=2.2.1->pyopenssl) (2.19)
Installing collected packages: pyopenssl

Successfully installed pyopenssl-18.0.0

(temp-python) manager@bl8vbox[manager] import urllib3.contrib.pyopenssl                                                                               [10:20PM]
(temp-python) manager@bl8vbox[manager] urllib3.contrib.pyopenssl.inject_into_urllib3()                                                                [10:25PM]
function> pip install gemtools
(temp-python) manager@bl8vbox[manager] pip install gemtools                                                                                           [10:27PM]
/home/manager/temp-python/local/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a 2.7.x release that supports hmac.compare_digest as soon as possible.
  utils.DeprecatedIn23,
Collecting gemtools
  Using cached https://files.pythonhosted.org/packages/8e/5a/3ed79b7649a5afc9fce8ed12298246069b7483d5e9a340248bc02ae660a2/Gemtools-1.7.1.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.34.tar.gz
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-K2SYTM/gemtools/setup.py", line 2, in <module>
        use_setuptools()
      File "distribute_setup.py", line 152, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "distribute_setup.py", line 131, in _do_download
        to_dir, download_delay)
      File "distribute_setup.py", line 201, in download_setuptools
        src = urlopen(url)
      File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
        return _opener.open(url, data, timeout)
      File "/usr/lib/python2.7/urllib2.py", line 410, in open
        response = meth(req, response)
      File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python2.7/urllib2.py", line 448, in error
        return self._call_chain(*args)
      File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    urllib2.HTTPError: HTTP Error 403: SSL is required
        ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-K2SYTM/gemtools/


Peter Dunn
Dist. Professor
Univ. of Wisconsin-Milwaukee
Dept. of Biological Sciences
3209 N. Maryland Ave.
Milwaukee, WI 53211
414-229-2253
http://people.uwm.edu/pdunn/
pdunn@uwm.edu<mailto:pdunn@uwm.edu>



On Oct 7, 2018, at 11:10 AM, Jordi <notifications@github.com<mailto:notifications@github.com>> wrote:

Probably you are trying to install under python 3. Try python 2.

--
Jordi Camps
jcamps@gmail.com<mailto:jcamps@gmail.com>

-----BEGIN GEEK CODE BLOCK-----
Version: 3.1
GCS/IT/S d-(+) s: a+ C++$>$ UL++ P---() L++ !E- W+ N+ !o K--? w+ !O !M !V
PS++() PE(-) Y+ !PGP>+++ t !5 X R tv(-) b+ DI+ D+ G e+++ h(---) r(--) y+**
------END GEEK CODE BLOCK------

**Comment by podunn58** [comment]
I did get this to install after fixing some folder permissions.  I also realized the program will not run on the Mac after running "file gemtools"
But now I am running into the same problem as weiiioyo on 29 March (#29).  The program stalls on the bam step, and I think it is because it cannot find the correct zlib library, even though I thought I had install it with sudo apt-get install make gcc libbz2-dev python-dev

Peter
